-- supabase/enable_rls.sql
-- Defense-in-depth: enable RLS on every table so the anon key has zero access.
-- The Next.js app uses the service role key (bypasses RLS), so app behavior is unchanged.
-- Idempotent and safe to re-run. IF EXISTS guards against any table that was renamed/removed.

-- Core
ALTER TABLE IF EXISTS users ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS otp_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS error_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS notification_prefs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS contributions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS analytics_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS api_perf ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS push_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS content_translations ENABLE ROW LEVEL SECURITY;

-- Content
ALTER TABLE IF EXISTS announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS announcement_reads ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS events ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS event_rsvps ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS document_access ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS document_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS faqs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS history_entries ENABLE ROW LEVEL SECURITY;

-- Subscriptions / Finance
ALTER TABLE IF EXISTS subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS expense_vouchers ENABLE ROW LEVEL SECURITY;

-- Tasks
ALTER TABLE IF EXISTS todos ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS todo_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS todo_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS todo_vouchers ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS todo_time_entries ENABLE ROW LEVEL SECURITY;

-- Teams
ALTER TABLE IF EXISTS teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS team_members ENABLE ROW LEVEL SECURITY;

-- Grievances / Suggestions
ALTER TABLE IF EXISTS grievances ENABLE ROW LEVEL SECURITY;

-- Polls / Resolutions / Wishlist
ALTER TABLE IF EXISTS polls ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS poll_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS resolutions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS resolution_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS wishlist_ideas ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS wishlist_upvotes ENABLE ROW LEVEL SECURITY;

-- Trainings
ALTER TABLE IF EXISTS trainings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS training_enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS trainer_invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS training_materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS training_material_access ENABLE ROW LEVEL SECURITY;

-- Food
ALTER TABLE IF EXISTS food_vendors ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS food_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS food_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS food_order_items ENABLE ROW LEVEL SECURITY;

-- Messages
ALTER TABLE IF EXISTS messages ENABLE ROW LEVEL SECURITY;

-- Group chat
ALTER TABLE IF EXISTS chat_channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS chat_channel_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS chat_message_mentions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS chat_message_reactions ENABLE ROW LEVEL SECURITY;

-- Logo vote
ALTER TABLE IF EXISTS logo_concepts ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS logo_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS logo_comments ENABLE ROW LEVEL SECURITY;

-- Feedback
ALTER TABLE IF EXISTS feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS feedback_prompts_shown ENABLE ROW LEVEL SECURITY;

-- Owner-only
ALTER TABLE IF EXISTS admin_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS admin_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS project_h_documents ENABLE ROW LEVEL SECURITY;

-- Volunteers
ALTER TABLE IF EXISTS volunteer_invites ENABLE ROW LEVEL SECURITY;
